name: enpal_app_code_challenge
description: "A sample Flutter app for Enpal coding challenge"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  http: ^1.3.0
  syncfusion_flutter_charts: ^28.2.3
  intl: ^0.20.2
  flutter_spinkit: ^5.2.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mockingjay: ^0.6.0
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/


